### ISSUE TITLE
Reg interface crashes on outputnode with no mask

### ISSUE THREAD

**Issue by evka85** [cms-gem-daq-project/xhal#39]
running outputnode command on a register without a mask crashes the reg_interface (probably just a simple check of "is None" is needed).

can be reproduced e.g. like this:
```
CTP7 > outputnode GEM_AMC.GEM_SYSTEM.CTRL.LINK_RESET
Name: GEM_AMC.GEM_SYSTEM.CTRL.LINK_RESET
Description: Reset the links to and from OHs and redo VFAT3 sync procedure
Address: 0x00900101
Permission: w
Mask:
Traceback (most recent call last):
  File "/mnt/persistent/texas/apps/reg_interface/reg_interface.py", line 379, in <module>
    prompt.cmdloop('Starting CTP7 Register Command Line Interface.')
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/mnt/persistent/texas/apps/reg_interface/reg_interface.py", line 17, in do_outputnode
    print node.output()
  File "/mnt/persistent/texas/apps/reg_interface/rw_reg.py", line 49, in output
    print 'Mask:','{0:#010x}'.format(self.mask)
ValueError: Unknown format code 'x' for object of type 'str'
```
Also please rename the outputnode command to something easier, like help or doc.

**Comment by mexanick** [comment]
please provide the code revision you use. The check if mask is not None has been provided as bugfix in a following commit:
https://github.com/cms-gem-daq-project/xhal/commit/e9f0991b877190cda08a0af54030c1e50bb1877e#diff-d987aa6cc9a9e309a935e79fa69bb381
