### ISSUE TITLE
Bug Report: Not possible to issue SCA reset from CTP7

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/xhal#62]
## Brief summary of issue

Unable to issue an SCA reset from the CTP7.  Previous functionality allowed this.

### Types of issue

- [X] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

Older version of the `sca.py` tool (e.g. see `eagle60`) worked from CTP7 without specifying a hostname.

## Current Behavior

When attempting to issue an SCA reset from CTP7 without supplying a hostname the help menu is displayed:

```
eagle61:~$ sca.py 0x3 r                                                                     
Usage: sca.py <card_name> <oh_mask> <instructions>
instructions:
  r:        SCA reset will be done
  h:        FPGA hard reset will be done
  hh:       FPGA hard reset will be asserted and held
  fpga-id:  FPGA ID will be read through JTAG
  sysmon:   Read FPGA sysmon data repeatedly
  program-fpga:   Program OH FPGA with a bitfile or an MCS file. Requires a parameter "bit" or "mcs" and a filename
```

When providing a hostname a `NameError` is returned:

```
eagle61:~$ sca.py eagle61 0x3 r
Open pickled address table if available  /mnt/persistent/gemdaq/xml/gem_amc_top.pickle...
Traceback (most recent call last):
  File "/mnt/persistent/gemdaq/python/reg_interface/sca.py", line 670, in <module>
    main()
  File "/mnt/persistent/gemdaq/python/reg_interface/sca.py", line 71, in main
    rpc_connect(sys.argv[1])
NameError: global name 'rpc_connect' is not defined
```

### Steps to Reproduce (for bugs)

1. Login to `eagle61`
2. Attempt to issue an SCA reset.

## Context (for feature requests)

Cannot program the OH FPGA via JTAG through SCA without issuing an SCA reset.  Previously functionality allowed this (unsure which commit because of the over-writing between @evka85 and @mexanick).

## Your Environment

* Version used: cac5edff4d9527f5d7be891072895b212beb6e12
* Shell used: `/bin/sh`

**Comment by bdorney** [comment]
For a `diff` between version of `sca.py` on `eagle60` and in the repo see [this comment](https://github.com/cms-gem-daq-project/xhal/issues/63#issuecomment-385471169)
