### ISSUE TITLE
Bug Report: Attempting to Program FPGA using JTAG via SCA Fails 

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/xhal#63]
## Brief summary of issue

Unable to program FPGA using JTAG through the SCA.  Previous functionality allowed this.

### Types of issue

- [X] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

Older version of the `sca.py` tool allowed programming FPGA without issue from CTP7 (see `eagle60`).

## Current Behavior

When attempting to program the FPGA's using JTAG via SCA from CTP7 a `ValueError` is returned:

```
eagle61:~$ sca.py 0x3 program-fpga bit /mnt/persistent/gemdaq/oh_fw/optohybrid_top.bit
Traceback (most recent call last):
  File "/mnt/persistent/gemdaq/python/reg_interface/sca.py", line 670, in <module>
    main()
  File "/mnt/persistent/gemdaq/python/reg_interface/sca.py", line 64, in main
    ohMask = parseInt(sys.argv[2])
  File "/mnt/persistent/gemdaq/python/reg_interface/rw_reg.py", line 357, in parseInt
    return int(string)
ValueError: invalid literal for int() with base 10: 'program-fpga'
```

### Steps to Reproduce (for bugs)

1. Log into `eagle61`
2. Attempt to program FPGA's using above command

## Context (for feature requests)

Cannot program the OH FPGA via JTAG through SCA. Previously functionality allowed this (unsure which commit because of the over-writing between @evka85 and @mexanick).

## Your Environment

* Version used: cac5edff4d9527f5d7be891072895b212beb6e12
* Shell used: `/bin/sh`

**Comment by bdorney** [comment]
Here's a diff between the version on `eagle60` and the version at 77e16f34255f903ea143e5c24903407ea63d197e
[diffSCAVersions.txt](https://github.com/cms-gem-daq-project/xhal/files/1961566/diffSCAVersions.txt)
