### ISSUE TITLE
Bug Report: issue w/reg_interface.py when launched from CTP7

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/xhal#71]
## Brief summary of issue

Ran into a problem when launching `reg_interface.py` on the card.  Not sure if this is due to an outdated version or a real bug.

### Types of issue

- [X] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

Should be able to launch `reg_interface.py` no problem.

## Current Behavior

```
eagle60:/mnt/persistent/gemdaq/xml$ reg_interface.py 
Traceback (most recent call last):
  File "/mnt/persistent/gemdaq/python/reg_interface/reg_interface.py", line 15, in <module>
    from ri_prompt_extended import *
  File "/mnt/persistent/gemdaq/python/reg_interface/ri_prompt_extended.py", line 1, in <module>
    import ri_prompt
  File "/mnt/persistent/gemdaq/python/reg_interface/ri_prompt.py", line 2, in <module>
    from rw_reg import *
  File "/mnt/persistent/gemdaq/python/reg_interface/rw_reg.py", line 10, in <module>
    lib = CDLL(os.getenv("GEM_PATH")+"/lib/librwreg.so")
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /mnt/persistent/gemdaq/lib/librwreg.so: file too short
```

### Steps to Reproduce (for bugs)

1. Login `eagle60`
2. Launch `reg_interface.py`

## Context (for feature requests)

`reg_interface.py` from the card should work.

## Your Environment

* Version used: ??? not sure if we have a way to tell this on the card ???
* Shell used: `/bin/sh`

**Comment by bdorney** [comment]
Wasn't sure if this should be cross-posted to `gemctp7user`.

**Comment by mexanick** [comment]
Closing as obsolete
