### ISSUE TITLE
Bug Report: jtagCommand() generates IndexError if input OH list is non-sequential

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/xhal#75]
## Brief summary of issue

Trying the sysmon command generates an `IndexError` error.

### Types of issue

- [X] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

It should work not generate an `IndexError`.

## Current Behavior

Following behavior was reported:

```
sca.py eagle63 0x2 sysmon
---- Setting JTAG CLK frequency to 10MHz (divider value = 0x1000000) ---- 
Initial value to write: 19, register GEM_AMC.SLOW_CONTROL.SCA.MANUAL_CONTROL.SCA_CMD.SCA_CMD_CHANNEL
Initial value to write: 144, register GEM_AMC.SLOW_CONTROL.SCA.MANUAL_CONTROL.SCA_CMD.SCA_CMD_COMMAND
Initial value to write: 4, register GEM_AMC.SLOW_CONTROL.SCA.MANUAL_CONTROL.SCA_CMD.SCA_CMD_LENGTH
Initial value to write: 16777216, register GEM_AMC.SLOW_CONTROL.SCA.MANUAL_CONTROL.SCA_CMD.SCA_CMD_DATA
Initial value to write: 1, register GEM_AMC.SLOW_CONTROL.SCA.MANUAL_CONTROL.SCA_CMD.SCA_CMD_EXECUTE
Traceback (most recent call last):
  File "/home/gemuser/DAQ/xhal/python/reg_interface/sca.py", line 709, in <module>
    main()
  File "/home/gemuser/DAQ/xhal/python/reg_interface/sca.py", line 128, in main
    coreTemp = ((adc1[oh] >> 6) & 0x3FF) * 503.975 / 1024.0-273.15
IndexError: list index out of range
```

### Steps to Reproduce (for bugs)

1. setup `xhal` env
2. `sca.py eagle63 0x2 sysmon`

## Context (for feature requests)

Should not generate a crash.

## Your Environment

* Version used: [3.2.2](https://github.com/cms-gem-daq-project/xhal/releases/tag/3.2.2)
* Shell used: `/bin/bash`

**Comment by bdorney** [comment]
This is actually a bug with `jtagCommand()`
